### ISSUE TITLE
Bee language name is duplicated!

### ISSUE THREAD

**Issue by elucian** [kkayal/bee#1]
Not a real issue but just so you know there is another language called Bee:
https://github.com/sage-code/bee/

If you like my design, let's merge the two projects. I see you like implementing in C. Make a compiler for Bee language using my specification. It will be so much more fun working with someone else.

**Comment by kkayal** [comment]
Thanks for inviting me to join your project! The sad truth is, I was unable to work on my bee compiler for a while and don't see how I can find the time in near future.. 

I had a quick look to yours and appreciate the effort you have put into it. So, I just decided to delete my project from github and this would solve the duplicated naming. Being in such an early stage, it would not be beneficial for anyone anyway ;-)

I wish you all the best!

**Comment by elucian** [comment]
Thanks.  You already made the effort to look at Bee spec, do you mind if I invite you in my organization?
We will appreciate your feedback. I look forward to connect with you on discord to chat or if you preffer reddit I look forward to see you there:
https://www.reddit.com/r/bee_lang/
https://discord.gg/jQTD8y

**Comment by kkayal** [comment]
Thanks! I hope to find some time, but cannot promise..
